package com.heroku.mapper;

import com.heroku.entity.Ticks;
import com.heroku.entity.TicksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TicksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticks
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int countByExample(TicksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticks
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int deleteByExample(TicksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticks
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insert(Ticks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticks
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insertSelective(Ticks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticks
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    List<Ticks> selectByExample(TicksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticks
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") Ticks record, @Param("example") TicksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticks
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExample(@Param("record") Ticks record, @Param("example") TicksExample example);
}