package com.heroku.mapper;

import com.heroku.entity.UPermission;
import com.heroku.entity.UPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int countByExample(UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int deleteByExample(UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insert(UPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insertSelective(UPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    List<UPermission> selectByExample(UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    UPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") UPermission record, @Param("example") UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExample(@Param("record") UPermission record, @Param("example") UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByPrimaryKeySelective(UPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_permission
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByPrimaryKey(UPermission record);
}