package com.heroku.mapper;

import com.heroku.entity.URole;
import com.heroku.entity.URoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface URoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int countByExample(URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int deleteByExample(URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insert(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insertSelective(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    List<URole> selectByExample(URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    URole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") URole record, @Param("example") URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExample(@Param("record") URole record, @Param("example") URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByPrimaryKeySelective(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_role
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByPrimaryKey(URole record);
}