package com.heroku.mapper;

import com.heroku.entity.UserMaster;
import com.heroku.entity.UserMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int countByExample(UserMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int deleteByExample(UserMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insert(UserMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insertSelective(UserMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    List<UserMaster> selectByExample(UserMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    UserMaster selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserMaster record, @Param("example") UserMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExample(@Param("record") UserMaster record, @Param("example") UserMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByPrimaryKeySelective(UserMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_master
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByPrimaryKey(UserMaster record);
}

