package com.heroku.mapper;

import com.heroku.entity.UUser;
import com.heroku.entity.UUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int countByExample(UUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int deleteByExample(UUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insert(UUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int insertSelective(UUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    List<UUser> selectByExample(UUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    UUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") UUser record, @Param("example") UUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByExample(@Param("record") UUser record, @Param("example") UUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByPrimaryKeySelective(UUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.u_user
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    int updateByPrimaryKey(UUser record);
}