package com.heroku.entity;

import java.util.Date;

public class Ticks {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticks.tick
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private Date tick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticks.tick
     *
     * @return the value of public.ticks.tick
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public Date getTick() {
        return tick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticks.tick
     *
     * @param tick the value for public.ticks.tick
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setTick(Date tick) {
        this.tick = tick;
    }
}