package com.heroku.entity;

public class UPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_permission.id
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_permission.url
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_permission.name
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_permission.id
     *
     * @return the value of public.u_permission.id
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_permission.id
     *
     * @param id the value for public.u_permission.id
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_permission.url
     *
     * @return the value of public.u_permission.url
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_permission.url
     *
     * @param url the value for public.u_permission.url
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_permission.name
     *
     * @return the value of public.u_permission.name
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_permission.name
     *
     * @param name the value for public.u_permission.name
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}