package com.heroku.entity;

public class URole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_role.id
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_role.name
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_role.type
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_role.id
     *
     * @return the value of public.u_role.id
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_role.id
     *
     * @param id the value for public.u_role.id
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_role.name
     *
     * @return the value of public.u_role.name
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_role.name
     *
     * @param name the value for public.u_role.name
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_role.type
     *
     * @return the value of public.u_role.type
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_role.type
     *
     * @param type the value for public.u_role.type
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}