package com.heroku.entity;

import java.io.Serializable;
import java.util.Date;

public class UserMaster implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_master.username
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_master.name
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_master.passwd
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_master.tick
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private Date tick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_master.username
     *
     * @return the value of public.user_master.username
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_master.username
     *
     * @param username the value for public.user_master.username
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_master.name
     *
     * @return the value of public.user_master.name
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_master.name
     *
     * @param name the value for public.user_master.name
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_master.passwd
     *
     * @return the value of public.user_master.passwd
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_master.passwd
     *
     * @param passwd the value for public.user_master.passwd
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_master.tick
     *
     * @return the value of public.user_master.tick
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public Date getTick() {
        return tick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_master.tick
     *
     * @param tick the value for public.user_master.tick
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setTick(Date tick) {
        this.tick = tick;
    }
}