package com.heroku.entity;

public class UUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_user_role.uid
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_user_role.rid
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_user_role.uid
     *
     * @return the value of public.u_user_role.uid
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_user_role.uid
     *
     * @param uid the value for public.u_user_role.uid
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_user_role.rid
     *
     * @return the value of public.u_user_role.rid
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_user_role.rid
     *
     * @param rid the value for public.u_user_role.rid
     *
     * @mbggenerated Sat Aug 26 12:41:35 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}